#### consul服务端口
server:
  port: 8006

#### consul服务注册名称
spring:
  application:
    name: consul-provider-payment
  #### consul注册中心地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}

